
#ontainer_name is not suported in the definition of a docker stack
#Also make sure the  docker swarm is initialized
#No reference to dockerfile should be declare here
version: '3'

networks:
  authmicroservice:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - authmicroservice


  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "4309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: kwafodev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - authmicroservice

  php:
    image: kwafo1/laraphphost
    volumes:
      - ./src:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - authmicroservice