version: '3'

networks:
  authmicroservice:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: "${COMPOSE_PROJECT_NAME}_microservice-nginx"
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ../authentication-src:/var/www/html
      - ./authentication-nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - authmicroservice
#  nginx:
#    image: linuxserver/letsencrypt
#    container_name: "${COMPOSE_PROJECT_NAME}_microservice-nginx"
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ../authentication-src:/var/www/html
#      - ./authentication-nginx/nginx.conf:/config/nginx/site-confs/default
#      - ./authentication-nginx/ssl.conf:/config/nginx/ssl.conf
#    depends_on:
#      - php
#      - mysql
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - URL=api.kwafonanadev.co.uk
#      - SUBDOMAINS=,
#      - VALIDATION=http
#      - STAGING=false #optional
#    networks:
#      - authmicroservice


  mysql:
    image: mysql:5.7.22
    container_name: "${COMPOSE_PROJECT_NAME}_microservice-mysql"
    restart: always
    tty: true
    ports:
      - "4309:3306"
    volumes:
      - ./authentication-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: kwafodev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - authmicroservice
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_microservice-php"
    volumes:
      - ../authentication-src:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - authmicroservice